import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import { UserProvider } from '@auth0/nextjs-auth0/client';
import SideMenu from './components/side-menu';
import TopBar from './components/top-bar';
import { EmployeeProvider } from './context/employeesContext';
import { GlobalProvider } from './context/globalContext';
import { PaymentProvider } from './context/paymentContext';
import type { Employee, SalaryLog } from './types';

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Payroll Management",
  description: "Generated by create next app",
};

async function getEmployees() {
  const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/employees`);
  const data: { employees: Employee[] } = await response.json();

  return {
    employees: data.employees
  };
};

async function getSalaryLogs() {
  const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/salaries/payment`);
  const data: { salaryLogs: SalaryLog[] } = await response.json();

  return {
    salaryLogs: data.salaryLogs
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { employees } = await getEmployees();
  const { salaryLogs } = await getSalaryLogs();

  return (
    <html lang="en">
      <UserProvider> 
        <GlobalProvider>
          <EmployeeProvider employeesData={employees}>
            <PaymentProvider paymentsData={salaryLogs}>
              <body className={montserrat.className}>
                <main className="flex h-screen w-screen p-2">
                  <SideMenu></SideMenu>
                  <div className="flex flex-col w-3/4 divide-y divide-slate-300">
                    <TopBar></TopBar>
                    {children}
                  </div>
                </main>
            </body>
            </PaymentProvider>
          </EmployeeProvider>
        </GlobalProvider>
      </UserProvider>
    </html>
  );
}