import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { UserProvider } from '@auth0/nextjs-auth0/client';
import SideMenu from "./components/side-menu";
import TopBar from "./components/top-bar";
import { EmployeeProvider } from './context/employeesContext';
import type { Employee } from './types';

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Payroll Management",
  description: "Generated by create next app",
};

async function getEmployees() {
  const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/employees`);
  const data: { employees: Employee[] } = await response.json();

  return {
    employees: data.employees
  };
};

// TODO: user provider?
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { employees } = await getEmployees();
  return (
    <html lang="en">
      <UserProvider>
        <EmployeeProvider employeesData={employees}>
        <body className={montserrat.className}>
          <main className="flex h-screen p-2">
            <SideMenu></SideMenu>
            <div className="flex flex-col w-full divide-y divide-slate-300">
              <TopBar></TopBar>
              {children}
            </div>
          </main>
        </body>
        </EmployeeProvider>
      </UserProvider>
    </html>
  );
}
